defaults:
  - dataset: nuscene_ego_exo
  #- dataset: nuscene #nuscene
  #- dataset: carla #carla
  #- dataset: seed4d #seed4d
  - model/encoder: epipolar
  - model/decoder: splatting_cuda
  - loss: [mse, lpips] #nuscene
  #- loss: [mse, mae] #carla
  #- loss: [mse, mae] #seed4d

wandb:
  #project: pixelsplat_nuScene_td1_rend1_test_nuscene_ckpt #nuscene 
  #project: pixelsplat_mae_test_carla #carla
  #project: pixelsplat_mae_test_seed4d #seed4d
  project: pixelsplat_nuscene_ego_exo #nuscene_ego_exo
  entity: scene-representation-group
  name: placeholder
  mode: online

mode: test

# GPU Configuration
#gpu:
#  device_id: 0  # value set here: 0,1,2,3 corresponds to physical GPU: 0,3,1,2 -> if you want to run on GPU 1, set this to 2

dataset:
  overfit_to_scene: null

data_loader:
  # Avoid having to spin up new processes to print out visualizations.
  train:
    num_workers: 16
    persistent_workers: true
    batch_size: 4
    seed: 1234
  test:
    num_workers: 4
    persistent_workers: false
    batch_size: 1
    seed: 2345
  val:
    num_workers: 1
    persistent_workers: true
    batch_size: 1
    seed: 3456

optimizer:
  lr: 1.5e-4
  warm_up_steps: 2000

checkpointing:
  #checkpoint for model trained on carla
  load: /app/code/pixelsplat_Sim2Real/outputs/carla_ckpt_basis/2024-11-04/14-35-32/checkpoints/epoch-315-step-300000.ckpt

  #checkpoint for model trained on carla and then on nuscenes
  #load: /app/code/pixelsplat_Sim2Real/outputs/carla_nuScenes_ckpt_basis/2024-11-08/09-31-36/checkpoints/epoch=318-step=400000.ckpt 
  every_n_train_steps: 20000
  save_top_k: -1

train:
  depth_mode: depth
  extended_visualization: false

test:
  #output_path: outputs/test/nuscenes_td2 #nuscene 
  #output_path: /app/outputs/ego_exo_carla_on_carla_ckpt5_fix #carla
  #output_path: /app/outputs/ego_exo_seed4dinvisible_on_carla_ckpt13_fix_100spawns #seed4d
  #output_path: /app/outputs/carla_nuscence_on_nuscene_0shot_td1_rend1_2
  #output_path: /app/outputs/ego_exo_nuscene_on_nuscene_ckpt_fix #nuscene_ego_exo 
  output_path: /app/outputs/ego_exo_nuscene_on_carla_ckpt_changed_transform_fov_means_images_switched #nuscene_ego_exo
  compute_scores: false
  save_image: true
  save_video: true
  eval_time_skip_steps: 0

seed: 111123

trainer:
  max_steps: -1
  val_check_interval: 500
  gradient_clip_val: 0.5