defaults:
  - dataset: seed4d #seed4d
  - model/encoder: epipolar
  - model/decoder: splatting_cuda
  - loss: [mse, mae] #seed4d/carla

wandb:
  project: pixelsplat_training 
  entity: scene-representation-group
  name: placeholder
  mode: online 

mode: test

dataset:
  overfit_to_scene: null

data_loader:
  # Avoid having to spin up new processes to print out visualizations.
  train:
    num_workers: 16 #1
    persistent_workers: true #false
    batch_size: 4
    seed: 1234
  test:
    num_workers: 4 #0
    persistent_workers: false
    batch_size: 1
    seed: 2345
  val:
    num_workers: 1 #0
    persistent_workers: true #false
    batch_size: 1
    seed: 3456

optimizer:
  lr: 1.5e-4
  warm_up_steps: 2000

checkpointing:
  #checkpoint for model trained on carla (from eyvaz)
  #load: /app/felix/code/pixelsplat_Sim2Real/outputs/checkpoints/initial_epoch-315-step-300000.ckpt

  #Experiment 0 Baseline 
  #load: /app/felix/code/pixelsplat_Sim2Real/outputs/2025-10-17/11-26-47/checkpoints/epoch=1260-step=300000.ckpt

  #Experiment II (Baseline-Mixed) 
  #load: /app/felix/code/pixelsplat_Sim2Real/outputs/2025-10-16/20-59-25/checkpoints/epoch=1260-step=300000.ckpt

  #Experiment 10
  #load: /app/code/pixelsplat_Sim2Real/outputs/2025-12-03/21-41-53/checkpoints/epoch=1260-step=300000.ckpt #10

  #Experiment 11
  #load: /app/code/pixelsplat_Sim2Real/outputs/2025-12-04/00-01-46/checkpoints/epoch=1260-step=300000.ckpt #11

  #Experiment 12 seed4d+nuscene ego views
  #load: /app/felix/code/pixelsplat_Sim2Real/outputs/2025-12-09/21-35-08/checkpoints/epoch=1260-step=300000.ckpt

  #Experiment 16 seed4d
  #load: /app/felix/code/pixelsplat_Sim2Real/outputs/2026-02-13/20-31-33/checkpoints/epoch=1260-step=300000.ckpt

  #Experiment 18 secogan 
  #load: /app/felix/code/pixelsplat_Sim2Real/outputs/2026-02-05/19-12-52/checkpoints/epoch=1260-step=300000.ckpt

  #Experiment 19 flux2 dataset 128x128
  #load: /app/felix/code/pixelsplat_Sim2Real/outputs/2026-02-12/04-00-51/checkpoints/epoch=1260-step=300000.ckpt

  #Experiment 1C SEED4D 192x192
  #load: /app/felix/code/pixelsplat_Sim2Real/outputs/2026-02-12/20-41-03/checkpoints/epoch=630-step=600000.ckpt

  #Experiment 1F FLUX2_9B 192x192
  #load: /app/felix/code/pixelsplat_Sim2Real/outputs/2026-02-12/20-23-11/checkpoints/epoch=630-step=600000.ckpt

  #Experiment 1S SecoGAN 192x192 
  #load: /app/felix/code/pixelsplat_Sim2Real/outputs/2026-02-28/23-46-59/checkpoints/epoch=268-step=255000.ckpt
  
  

  every_n_train_steps: 20000 
  save_top_k: -1

train:
  depth_mode: depth
  extended_visualization: false

test:
  
  output_path: /app/outputs/pixelsplat 
 
  compute_scores: false
  save_image: true
  save_video: true
  eval_time_skip_steps: 0

seed: 111123

trainer:
  max_steps: -1
  val_check_interval: 500
  gradient_clip_val: 0.5

