defaults:
  - dataset: carla
  - model/encoder: epipolar
  - model/decoder: splatting_cuda
  - loss: [mse, mae]

wandb:
  project: pixelsplat_mae_test
  entity: scene-representation-group
  name: placeholder
  mode: online

mode: test

dataset:
  overfit_to_scene: null

data_loader:
  # Avoid having to spin up new processes to print out visualizations.
  train:
    num_workers: 16
    persistent_workers: true
    batch_size: 4
    seed: 1234
  test:
    num_workers: 4
    persistent_workers: false
    batch_size: 1
    seed: 2345
  val:
    num_workers: 1
    persistent_workers: true
    batch_size: 1
    seed: 3456

optimizer:
  lr: 1.5e-4
  warm_up_steps: 2000

checkpointing:
  #load: "/app/new/sshELF_Benchmarks/pixelsplat/outputs/2024-11-04/14-35-32/checkpoints/epoch=315-step=300000.ckpt"
  #load: /app/code/code/pixelsplat/outputs/2024-11-04/14-35-32/checkpoints/epoch=315-step=300000.ckpt
  load: /app/code/code/pixelsplat/outputs/2024-11-04/14-35-32/checkpoints/epoch-315-step-300000.ckpt
  every_n_train_steps: 20000
  save_top_k: -1

train:
  depth_mode: depth
  extended_visualization: false

test:
  output_path: outputs/test
  compute_scores: false
  save_image: true
  save_video: true
  eval_time_skip_steps: 0

seed: 111123

trainer:
  max_steps: -1
  val_check_interval: 500
  gradient_clip_val: 0.5
