name: train_nuscene_view

num_target_views: 2 # ego-exo, for ego-ego the value is: 1
num_context_views: 6
augment: false
augment_p: 0.5
augment_mask_count: 5
nuscene_td: 2                      # is different than carla version
nuscene_render_k: 2              # determines the index of render view
nuscene_version: v1.0-trainval     # is different than carla version
# If you want to hard-code context views, do so here.
context_views: null
target_views: null
# #
input_context_resolution: 256 #128 #64 #256
output_target_resolution: 256 #128 #64 #256