name: nuscene
#############################################################
defaults:
  - train_view_sampler: train_nuscene_view
  - eval_view_sampler: eval_nuscene_view
#############################################################
background_color: [1.0, 1.0, 1.0]
#############################################################
nuscene_lidar_point_num: 40000
max_fov: 90.0
z_near: 0.007
z_far: 70.0
#############################################################
# We will differentiate between input and output image shapes
# and will transform intrinsics matrices correspondingly
# as we are working with tensors of consistent resolutions, it is
# better to setup context&target views to the same resolution